version: "1.0"
info:
  model: int-scaffold
packages:
- name: Txc2025Project
  gitServerName: davepemberton
  gitUrl: https://github.com/dave-pemberton-ibm
  gitUsername: dave-pemberton-ibm
  gitBranch: main
